export const MOVIMIENTOS = {
  pageTitle: 'Movimientos',
  pageDescription: 'Registra y revisa tus ingresos y gastos del mes.',
  summaryTitle: 'Resumen del mes',
  summaryDescription: 'Consulta el balance neto y administra tus movimientos del período.',
  newTitle: 'Nuevo movimiento',
  newDescription: 'Carga un ingreso o gasto con la fecha, categoría y monto.',
  monthLabel: 'Mes',
  createAction: 'Nuevo movimiento',
  editTitle: 'Editar movimiento',
  editDescription: 'Actualiza los datos del movimiento seleccionado.',
  emptyTitle: 'Todavía no hay movimientos en este mes',
  emptyDescription: 'Empieza cargando tu primer ingreso o gasto para este período.',
  listTitle: 'Historial del mes',
  listDescription: 'Solo ves movimientos propios del mes seleccionado.',
  form: {
    typeLabel: 'Tipo',
    amountLabel: 'Monto',
    dateLabel: 'Fecha',
    categoryLabel: 'Categoría',
    noteLabel: 'Nota',
    notePlaceholder: 'Opcional: agrega un detalle breve',
    submitCreate: 'Guardar movimiento',
    submitUpdate: 'Guardar cambios',
    cancel: 'Cancelar',
    dateHelp: 'Solo se permiten fechas de hoy o anteriores.',
  },
  types: {
    income: 'Ingreso',
    expense: 'Gasto',
  },
  actions: {
    edit: 'Editar',
    delete: 'Eliminar',
    closeEditor: 'Cerrar edición',
    backToList: 'Volver a movimientos',
  },
  summary: {
    netBalance: 'Balance neto',
    selectedHint: 'Movimiento seleccionado',
    totalMovimientos: (count: number) => `${count} movimientos`,
  },
  feedback: {
    loading: 'Cargando movimientos...',
    loadError: 'No se pudieron cargar los movimientos.',
    createSuccess: 'Movimiento guardado correctamente',
    updateSuccess: 'Movimiento actualizado correctamente',
    deleteSuccess: 'Movimiento eliminado correctamente',
    deleteConfirm: '¿Seguro que quieres eliminar este movimiento?',
  },
  editorPlaceholderTitle: 'Selecciona un movimiento para editar',
  editorPlaceholderDescription:
    'Puedes editar o eliminar cualquier movimiento propio desde la lista del mes.',
} as const;
