export const MOVIMIENTOS = {
  newTitle: 'Nuevo movimiento',
  newDescription: 'Carga un ingreso o gasto con la fecha, categoría y monto.',
  allTimeTitle: 'Todo el historial',
  createAction: 'Nuevo movimiento',
  editTitle: 'Editar movimiento',
  editDescription: 'Actualiza los datos del movimiento seleccionado.',
  searchPlaceholder: 'Buscar por tipo, categoría, monto o nota',
  searchClearLabel: 'Limpiar búsqueda',
  emptyTitle: 'Todavía no hay movimientos en este mes',
  emptyDescription: 'Empieza cargando tu primer ingreso o gasto para este período.',
  emptySearchTitle: 'No encontramos movimientos con esa búsqueda',
  emptySearchDescription: 'Prueba con otro tipo, categoría, monto o una palabra de la nota.',
  form: {
    typeLabel: 'Tipo',
    amountLabel: 'Monto',
    dateLabel: 'Fecha',
    categoryLabel: 'Categoría',
    noteLabel: 'Nota',
    notePlaceholder: 'Opcional: agrega un detalle breve',
    submitCreate: 'Guardar movimiento',
    submitUpdate: 'Guardar cambios',
    cancel: 'Cancelar',
    dateHelp: 'Solo se permiten fechas de hoy o anteriores.',
  },
  types: {
    income: 'Ingreso',
    expense: 'Gasto',
  },
  nav: {
    prev: 'Mes anterior',
    next: 'Mes siguiente',
    movLabel: 'mov.',
  },
  actions: {
    edit: 'Editar',
    delete: 'Eliminar',
    backToList: 'Volver a movimientos',
    menuLabel: 'Acciones del movimiento',
  },
  feedback: {
    loading: 'Cargando movimientos...',
    loadError: 'No se pudieron cargar los movimientos.',
    createSuccess: 'Movimiento guardado correctamente',
    updateSuccess: 'Movimiento actualizado correctamente',
    deleteSuccess: 'Movimiento eliminado correctamente',
    deleteConfirm: '¿Seguro que quieres eliminar este movimiento?',
  },
} as const;
