/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/_settings'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SettingsSettingsRouteImport } from './routes/_settings/settings'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as SettingsSettingsIndexRouteImport } from './routes/_settings/settings/index'
import { Route as AppTransactionsIndexRouteImport } from './routes/_app/transactions/index'
import { Route as SettingsSettingsSecurityRouteImport } from './routes/_settings/settings/security'
import { Route as SettingsSettingsPreferencesRouteImport } from './routes/_settings/settings/preferences'
import { Route as SettingsSettingsNotificationsRouteImport } from './routes/_settings/settings/notifications'
import { Route as SettingsSettingsDataRouteImport } from './routes/_settings/settings/data'
import { Route as AppTransactionsNewRouteImport } from './routes/_app/transactions/new'
import { Route as AppTransactionsIdRouteImport } from './routes/_app/transactions/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsSettingsRoute = SettingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const SettingsSettingsIndexRoute = SettingsSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const AppTransactionsIndexRoute = AppTransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const SettingsSettingsSecurityRoute =
  SettingsSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsPreferencesRoute =
  SettingsSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsNotificationsRoute =
  SettingsSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SettingsSettingsRoute,
  } as any)
const SettingsSettingsDataRoute = SettingsSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsSettingsRoute,
} as any)
const AppTransactionsNewRoute = AppTransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTransactionsRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/settings': typeof SettingsSettingsRouteWithChildren
  '/transactions/$id': typeof AppTransactionsIdRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/settings/data': typeof SettingsSettingsDataRoute
  '/settings/notifications': typeof SettingsSettingsNotificationsRoute
  '/settings/preferences': typeof SettingsSettingsPreferencesRoute
  '/settings/security': typeof SettingsSettingsSecurityRoute
  '/transactions/': typeof AppTransactionsIndexRoute
  '/settings/': typeof SettingsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
  '/transactions/new': typeof AppTransactionsNewRoute
  '/settings/data': typeof SettingsSettingsDataRoute
  '/settings/notifications': typeof SettingsSettingsNotificationsRoute
  '/settings/preferences': typeof SettingsSettingsPreferencesRoute
  '/settings/security': typeof SettingsSettingsSecurityRoute
  '/transactions': typeof AppTransactionsIndexRoute
  '/settings': typeof SettingsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_settings': typeof SettingsRouteWithChildren
  '/_app/transactions': typeof AppTransactionsRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_settings/settings': typeof SettingsSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/transactions/$id': typeof AppTransactionsIdRoute
  '/_app/transactions/new': typeof AppTransactionsNewRoute
  '/_settings/settings/data': typeof SettingsSettingsDataRoute
  '/_settings/settings/notifications': typeof SettingsSettingsNotificationsRoute
  '/_settings/settings/preferences': typeof SettingsSettingsPreferencesRoute
  '/_settings/settings/security': typeof SettingsSettingsSecurityRoute
  '/_app/transactions/': typeof AppTransactionsIndexRoute
  '/_settings/settings/': typeof SettingsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/transactions'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/settings'
    | '/transactions/$id'
    | '/transactions/new'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/security'
    | '/transactions/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/transactions/$id'
    | '/transactions/new'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/security'
    | '/transactions'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_settings'
    | '/_app/transactions'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_settings/settings'
    | '/_app/'
    | '/_app/transactions/$id'
    | '/_app/transactions/new'
    | '/_settings/settings/data'
    | '/_settings/settings/notifications'
    | '/_settings/settings/preferences'
    | '/_settings/settings/security'
    | '/_app/transactions/'
    | '/_settings/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_settings/settings': {
      id: '/_settings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsSettingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_settings/settings/': {
      id: '/_settings/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsSettingsIndexRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_app/transactions/': {
      id: '/_app/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AppTransactionsIndexRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_settings/settings/security': {
      id: '/_settings/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSettingsSecurityRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/preferences': {
      id: '/_settings/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsSettingsPreferencesRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/notifications': {
      id: '/_settings/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsSettingsNotificationsRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_settings/settings/data': {
      id: '/_settings/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsSettingsDataRouteImport
      parentRoute: typeof SettingsSettingsRoute
    }
    '/_app/transactions/new': {
      id: '/_app/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AppTransactionsNewRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
    '/_app/transactions/$id': {
      id: '/_app/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
  }
}

interface AppTransactionsRouteChildren {
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
  AppTransactionsNewRoute: typeof AppTransactionsNewRoute
  AppTransactionsIndexRoute: typeof AppTransactionsIndexRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsIdRoute: AppTransactionsIdRoute,
  AppTransactionsNewRoute: AppTransactionsNewRoute,
  AppTransactionsIndexRoute: AppTransactionsIndexRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SettingsSettingsRouteChildren {
  SettingsSettingsDataRoute: typeof SettingsSettingsDataRoute
  SettingsSettingsNotificationsRoute: typeof SettingsSettingsNotificationsRoute
  SettingsSettingsPreferencesRoute: typeof SettingsSettingsPreferencesRoute
  SettingsSettingsSecurityRoute: typeof SettingsSettingsSecurityRoute
  SettingsSettingsIndexRoute: typeof SettingsSettingsIndexRoute
}

const SettingsSettingsRouteChildren: SettingsSettingsRouteChildren = {
  SettingsSettingsDataRoute: SettingsSettingsDataRoute,
  SettingsSettingsNotificationsRoute: SettingsSettingsNotificationsRoute,
  SettingsSettingsPreferencesRoute: SettingsSettingsPreferencesRoute,
  SettingsSettingsSecurityRoute: SettingsSettingsSecurityRoute,
  SettingsSettingsIndexRoute: SettingsSettingsIndexRoute,
}

const SettingsSettingsRouteWithChildren =
  SettingsSettingsRoute._addFileChildren(SettingsSettingsRouteChildren)

interface SettingsRouteChildren {
  SettingsSettingsRoute: typeof SettingsSettingsRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsRoute: SettingsSettingsRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
