export const TRANSACTIONS = {
  newTitle: 'Nueva transacción',
  newDescription: 'Carga un ingreso o gasto con la fecha, categoría y monto.',
  allTimeTitle: 'Todo el historial',
  createAction: 'Nueva transacción',
  editTitle: 'Editar transacción',
  editDescription: 'Actualiza los datos de la transacción seleccionada.',
  searchPlaceholder: 'Buscar por tipo, categoría, monto o nota',
  searchClearLabel: 'Limpiar búsqueda',
  emptyTitle: 'Todavía no hay transacciones en este mes',
  emptyDescription: 'Empieza cargando tu primer ingreso o gasto para este período.',
  emptySearchTitle: 'No encontramos transacciones con esa búsqueda',
  emptySearchDescription: 'Prueba con otro tipo, categoría, monto o una palabra de la nota.',
  form: {
    typeLabel: 'Tipo',
    amountLabel: 'Monto',
    dateLabel: 'Fecha',
    categoryLabel: 'Categoría',
    noteLabel: 'Nota',
    notePlaceholder: 'Opcional: agrega un detalle breve',
    submitCreate: 'Guardar transacción',
    submitUpdate: 'Guardar cambios',
    cancel: 'Cancelar',
    dateHelp: 'Solo se permiten fechas de hoy o anteriores.',
  },
  types: {
    income: 'Ingreso',
    expense: 'Gasto',
  },
  nav: {
    prev: 'Mes anterior',
    next: 'Mes siguiente',
    movLabel: 'mov.',
  },
  actions: {
    edit: 'Editar',
    delete: 'Eliminar',
    backToList: 'Volver a transacciones',
    menuLabel: 'Acciones de la transacción',
  },
  feedback: {
    loading: 'Cargando transacciones...',
    loadError: 'No se pudieron cargar las transacciones.',
    createSuccess: 'Transacción guardada correctamente',
    updateSuccess: 'Transacción actualizada correctamente',
    deleteSuccess: 'Transacción eliminada correctamente',
    deleteConfirm: '¿Seguro que quieres eliminar esta transacción?',
  },
} as const;
